### ISSUE TITLE
Cop-Bonus berechnen

### ISSUE THREAD

**Issue by tklein1801** [LandminenTester/ReallifeRPG-Farmrechner#1]
Moin, wäre doch klasse wenn für Items der Klasse 4 der Cop-Bonus berechnet für würde um zu schauen wie viel man wirklich bei diesem Item verdienen würde.

**Comment by LandminenTester** [comment]
Dafür brauche ich einen Wert mit dem ich das berechnen kann

**Comment by tklein1801** [comment]
[Hier](https://github.com/tklein1801/A3RLRPG-Infopanel/blob/10a15f4a7b9a8b01f70b2def391fc548cb4737e0/src/config.json#L17) sind meine Werte die ich dafür verwende. Die Werte ab 17 konnte ich bisher nicht berechnen weshalb die alle gleich sind.

**Comment by LandminenTester** [comment]
Wird implementiert

**Comment by LandminenTester** [comment]
Wurde implementiert und ist in der Beta V0.2 beinhaltet.
Danke für die Werte!
